TEST_VALUE:
  name: cookie
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a4abf72e4e3f900b
  FEISHU_APP_SECRET: zzUW3jkHDaYA1NhSS00gEeVYMGyLRAHs
MYSQL_CONFIG:
  name: 'fast_gateway_test'
  port: 3306
  host: 'localhost'
  username: 'user'
  password: 'pass'
  database: 'fast_gateway_test'
  entities: 'mysql'
  logging: false
  synchronize: true
