TEST_VALUE:
  name: cookie
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a4abf72e4e3f900b
  FEISHU_APP_SECRET: zzUW3jkHDaYA1NhSS00gEeVYMGyLRAHs
MONGODB_CONFIG:
  name: 'fast_gateway_test'
  type: mongodb
  url: 'mongodb://localhost:27017'
  username: 'admin'
  password: 'password'
  database: 'fast_gateway_test'
  entities: 'mongo'
  logging: false
  synchronize: true
